sudo: false

language: ruby

rvm:
  - 2.6.0

services:
  - docker

before_install:
  - docker build -t openssl ./interop
  - gem install bundler -v 2.0.1
  - bundle install
  - docker images

script: bundle exec rake
