sudo: false

language: ruby

rvm:
  - 2.6.0

services:
  - docker

addons:
  apt:
    packages:
      - lsof

before_install:
  - gem install bundler -v 2.0.1
  - bundle install
  - docker build -t openssl ./interop

script: bundle exec rake
